// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// normalize_blast_tsv_cpp
void normalize_blast_tsv_cpp(std::string infile, std::string outfile, int genome_width, bool drop_self);
RcppExport SEXP _OrthoPaiR_normalize_blast_tsv_cpp(SEXP infileSEXP, SEXP outfileSEXP, SEXP genome_widthSEXP, SEXP drop_selfSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type infile(infileSEXP);
    Rcpp::traits::input_parameter< std::string >::type outfile(outfileSEXP);
    Rcpp::traits::input_parameter< int >::type genome_width(genome_widthSEXP);
    Rcpp::traits::input_parameter< bool >::type drop_self(drop_selfSEXP);
    normalize_blast_tsv_cpp(infile, outfile, genome_width, drop_self);
    return R_NilValue;
END_RCPP
}
// rbh_from_sorted_norm_cpp
void rbh_from_sorted_norm_cpp(std::string sorted_norm_fn, std::string out_fn);
RcppExport SEXP _OrthoPaiR_rbh_from_sorted_norm_cpp(SEXP sorted_norm_fnSEXP, SEXP out_fnSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type sorted_norm_fn(sorted_norm_fnSEXP);
    Rcpp::traits::input_parameter< std::string >::type out_fn(out_fnSEXP);
    rbh_from_sorted_norm_cpp(sorted_norm_fn, out_fn);
    return R_NilValue;
END_RCPP
}
// rbh_shortest_path
List rbh_shortest_path(IntegerVector qgeneid, IntegerVector sgeneid, IntegerVector q_chr, IntegerVector s_chr, IntegerVector anchor_qgeneid, IntegerVector anchor_sgeneid, IntegerVector anchor_q_chr, IntegerVector anchor_s_chr, bool omit_zero);
RcppExport SEXP _OrthoPaiR_rbh_shortest_path(SEXP qgeneidSEXP, SEXP sgeneidSEXP, SEXP q_chrSEXP, SEXP s_chrSEXP, SEXP anchor_qgeneidSEXP, SEXP anchor_sgeneidSEXP, SEXP anchor_q_chrSEXP, SEXP anchor_s_chrSEXP, SEXP omit_zeroSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type qgeneid(qgeneidSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type sgeneid(sgeneidSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type q_chr(q_chrSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type s_chr(s_chrSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type anchor_qgeneid(anchor_qgeneidSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type anchor_sgeneid(anchor_sgeneidSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type anchor_q_chr(anchor_q_chrSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type anchor_s_chr(anchor_s_chrSEXP);
    Rcpp::traits::input_parameter< bool >::type omit_zero(omit_zeroSEXP);
    rcpp_result_gen = Rcpp::wrap(rbh_shortest_path(qgeneid, sgeneid, q_chr, s_chr, anchor_qgeneid, anchor_sgeneid, anchor_q_chr, anchor_s_chr, omit_zero));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_OrthoPaiR_normalize_blast_tsv_cpp", (DL_FUNC) &_OrthoPaiR_normalize_blast_tsv_cpp, 4},
    {"_OrthoPaiR_rbh_from_sorted_norm_cpp", (DL_FUNC) &_OrthoPaiR_rbh_from_sorted_norm_cpp, 2},
    {"_OrthoPaiR_rbh_shortest_path", (DL_FUNC) &_OrthoPaiR_rbh_shortest_path, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_OrthoPaiR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
