# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Maximal colorful connected sets (internal). Vertices are rows of \code{vids} (sorted names).
#' @param vids_sorted Character vector of vertex names, sorted.
#' @param el Integer matrix \code{n_e x 2}, 0-based indices into \code{vids_sorted}.
#' @param color Integer vector (0-based colour id per vertex row), length \code{length(vids_sorted)}.
cpp_em_max_cc_subg <- function(vids_sorted, el, color) {
    .Call('_OrthoPaiR_cpp_em_max_cc_subg', PACKAGE = 'OrthoPaiR', vids_sorted, el, color)
}

