# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

R_igraph_to_SEXP <- function(graph) {
    .Call('_Synog_R_igraph_to_SEXP', PACKAGE = 'Synog', graph)
}

calculate_distances <- function(graph_ptr, qseqid, sseqid) {
    .Call('_Synog_calculate_distances', PACKAGE = 'Synog', graph_ptr, qseqid, sseqid)
}

