# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

normalize_blast_tsv_cpp <- function(infile, outfile, genome_width = 4L, drop_self = TRUE) {
    invisible(.Call(`_OrthoPaiR_normalize_blast_tsv_cpp`, infile, outfile, genome_width, drop_self))
}

rbh_from_sorted_norm_cpp <- function(sorted_norm_fn, out_fn) {
    invisible(.Call(`_OrthoPaiR_rbh_from_sorted_norm_cpp`, sorted_norm_fn, out_fn))
}

rbh_shortest_path <- function(qgeneid, sgeneid, q_chr, s_chr, anchor_qgeneid, anchor_sgeneid, anchor_q_chr, anchor_s_chr, omit_zero = FALSE) {
    .Call(`_OrthoPaiR_rbh_shortest_path`, qgeneid, sgeneid, q_chr, s_chr, anchor_qgeneid, anchor_sgeneid, anchor_q_chr, anchor_s_chr, omit_zero)
}

